INSERT INTO category (name) VALUES ('Apparel');
INSERT INTO category (name) VALUES ('Accessories');
INSERT INTO category (name) VALUES ('Footwear');
INSERT INTO category (name) VALUES ('Personal Care');
INSERT INTO category (name) VALUES ('Free Items');
INSERT INTO category (name) VALUES ('Sporting Goods');
INSERT INTO category (name) VALUES ('Home');
-- INSERT INTO category (name) VALUES ('Apparel');
-- INSERT INTO category (name) VALUES ('Accessories');
-- INSERT INTO category (name) VALUES ('Footwear');
-- INSERT INTO category (name) VALUES ('Personal Care');
-- INSERT INTO category (name) VALUES ('Free Items');
-- INSERT INTO category (name) VALUES ('Sporting Goods');
-- INSERT INTO category (name) VALUES ('Home');
