INSERT INTO subcategory (name) VALUES ('Topwear');
INSERT INTO subcategory (name) VALUES ('Bottomwear');
INSERT INTO subcategory (name) VALUES ('Watches');
INSERT INTO subcategory (name) VALUES ('Socks');
INSERT INTO subcategory (name) VALUES ('Shoes');
INSERT INTO subcategory (name) VALUES ('Belts');
INSERT INTO subcategory (name) VALUES ('Flip Flops');
INSERT INTO subcategory (name) VALUES ('Bags');
INSERT INTO subcategory (name) VALUES ('Innerwear');
INSERT INTO subcategory (name) VALUES ('Sandal');
INSERT INTO subcategory (name) VALUES ('Shoe Accessories');
INSERT INTO subcategory (name) VALUES ('Fragrance');
INSERT INTO subcategory (name) VALUES ('Jewellery');
INSERT INTO subcategory (name) VALUES ('Lips');
INSERT INTO subcategory (name) VALUES ('Saree');
INSERT INTO subcategory (name) VALUES ('Eyewear');
INSERT INTO subcategory (name) VALUES ('Scarves');
INSERT INTO subcategory (name) VALUES ('Dress');
INSERT INTO subcategory (name) VALUES ('Loungewear and Nightwear');
INSERT INTO subcategory (name) VALUES ('Wallets');
INSERT INTO subcategory (name) VALUES ('Apparel Set');
INSERT INTO subcategory (name) VALUES ('Headwear');
INSERT INTO subcategory (name) VALUES ('Mufflers');
INSERT INTO subcategory (name) VALUES ('Skin Care');
INSERT INTO subcategory (name) VALUES ('Makeup');
INSERT INTO subcategory (name) VALUES ('Free Gifts');
INSERT INTO subcategory (name) VALUES ('Ties');
INSERT INTO subcategory (name) VALUES ('Accessories');
INSERT INTO subcategory (name) VALUES ('Nails');
INSERT INTO subcategory (name) VALUES ('Beauty Accessories');
INSERT INTO subcategory (name) VALUES ('Water Bottle');
INSERT INTO subcategory (name) VALUES ('Skin');
INSERT INTO subcategory (name) VALUES ('Eyes');
INSERT INTO subcategory (name) VALUES ('Bath and Body');
INSERT INTO subcategory (name) VALUES ('Gloves');
INSERT INTO subcategory (name) VALUES ('Sports Accessories');
INSERT INTO subcategory (name) VALUES ('Cufflinks');
INSERT INTO subcategory (name) VALUES ('Sports Equipment');
INSERT INTO subcategory (name) VALUES ('Stoles');
INSERT INTO subcategory (name) VALUES ('Hair');
INSERT INTO subcategory (name) VALUES ('Perfumes');
INSERT INTO subcategory (name) VALUES ('Home Furnishing');
INSERT INTO subcategory (name) VALUES ('Umbrellas');
INSERT INTO subcategory (name) VALUES ('Wristbands');
INSERT INTO subcategory (name) VALUES ('Vouchers');
