INSERT INTO subcategory SET name = 'Topwear', category_id = (SELECT category_id from category WHERE category.name = 'Apparel');
INSERT INTO subcategory SET name = 'Bottomwear', category_id = (SELECT category_id from category WHERE category.name = 'Apparel');
INSERT INTO subcategory SET name = 'Watches', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Socks', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Shoes', category_id = (SELECT category_id from category WHERE category.name = 'Footwear');
INSERT INTO subcategory SET name = 'Belts', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Flip Flops', category_id = (SELECT category_id from category WHERE category.name = 'Footwear');
INSERT INTO subcategory SET name = 'Bags', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Innerwear', category_id = (SELECT category_id from category WHERE category.name = 'Apparel');
INSERT INTO subcategory SET name = 'Sandal', category_id = (SELECT category_id from category WHERE category.name = 'Footwear');
INSERT INTO subcategory SET name = 'Shoe Accessories', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Fragrance', category_id = (SELECT category_id from category WHERE category.name = 'Personal Care');
INSERT INTO subcategory SET name = 'Jewellery', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Lips', category_id = (SELECT category_id from category WHERE category.name = 'Personal Care');
INSERT INTO subcategory SET name = 'Saree', category_id = (SELECT category_id from category WHERE category.name = 'Apparel');
INSERT INTO subcategory SET name = 'Eyewear', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Scarves', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Dress', category_id = (SELECT category_id from category WHERE category.name = 'Apparel');
INSERT INTO subcategory SET name = 'Loungewear and Nightwear', category_id = (SELECT category_id from category WHERE category.name = 'Apparel');
INSERT INTO subcategory SET name = 'Wallets', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Apparel Set', category_id = (SELECT category_id from category WHERE category.name = 'Apparel');
INSERT INTO subcategory SET name = 'Headwear', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Mufflers', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Skin Care', category_id = (SELECT category_id from category WHERE category.name = 'Personal Care');
INSERT INTO subcategory SET name = 'Makeup', category_id = (SELECT category_id from category WHERE category.name = 'Personal Care');
INSERT INTO subcategory SET name = 'Free Gifts', category_id = (SELECT category_id from category WHERE category.name = 'Free Items');
INSERT INTO subcategory SET name = 'Ties', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Accessories', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Nails', category_id = (SELECT category_id from category WHERE category.name = 'Personal Care');
INSERT INTO subcategory SET name = 'Beauty Accessories', category_id = (SELECT category_id from category WHERE category.name = 'Personal Care');
INSERT INTO subcategory SET name = 'Water Bottle', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Skin', category_id = (SELECT category_id from category WHERE category.name = 'Personal Care');
INSERT INTO subcategory SET name = 'Eyes', category_id = (SELECT category_id from category WHERE category.name = 'Personal Care');
INSERT INTO subcategory SET name = 'Bath and Body', category_id = (SELECT category_id from category WHERE category.name = 'Personal Care');
INSERT INTO subcategory SET name = 'Gloves', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Sports Accessories', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Cufflinks', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Sports Equipment', category_id = (SELECT category_id from category WHERE category.name = 'Sporting Goods');
INSERT INTO subcategory SET name = 'Stoles', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Hair', category_id = (SELECT category_id from category WHERE category.name = 'Personal Care');
INSERT INTO subcategory SET name = 'Perfumes', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Home Furnishing', category_id = (SELECT category_id from category WHERE category.name = 'Home');
INSERT INTO subcategory SET name = 'Umbrellas', category_id = (SELECT category_id from category WHERE category.name = 'Accessories');
INSERT INTO subcategory SET name = 'Wristbands', category_id = (SELECT category_id from category WHERE category.name = 'Sporting Goods');
INSERT INTO subcategory SET name = 'Vouchers', category_id = (SELECT category_id from category WHERE category.name = 'Free Items');
