# Generated by Django 3.2.8 on 2021-10-11 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_gender', models.CharField(max_length=45)),
                ('product_quantity', models.IntegerField()),
                ('product_color', models.CharField(max_length=45)),
                ('product_type', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_link', models.CharField(max_length=200)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
