# Generated by Django 3.2.9 on 2021-11-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211011_0432'),
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_contains', to='favorite.favorite')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_contains', to='product.product')),
            ],
            options={
                'db_table': 'contains',
                'unique_together': {('favorite', 'product')},
            },
        ),
    ]
