# Generated by Django 3.2.9 on 2021-11-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_contains'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contains',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='contains',
            constraint=models.UniqueConstraint(fields=('favorite', 'product'), name='unique'),
        ),
    ]
